fix orocos install
acxz/pkgbuilds pull request #132
Opened 2021-06-18 06:54 UTC by AchmadFathoni

2021-06-18 16:28 UTC, acxz requested changes
Just a little nitpick, but looks good otherwise.

2021-06-18 16:28 UTC, acxz commented on orocos-kdl-python/PKGBUILD
> +        -DCMAKE_BUILD_TYPE=Release \
We should not be using the Release mode see: https://wiki.archlinux.org/title/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag

2021-06-18 16:28 UTC, acxz commented on orocos-kdl/PKGBUILD
> +        -DCMAKE_BUILD_TYPE=Release \
Same as above

2021-06-19 05:56 UTC, AchmadFathoni commented
Removed the release flag

2021-06-19 06:53 UTC, acxz approved these changes

2021-06-19 06:53 UTC, acxz commented
thx for iterating!

2021-06-19 06:53 UTC, merged