ogre-1.9: remove versions from provides
acxz/pkgbuilds pull request #153
Opened 2021-12-12 12:05 UTC by rmsc

Ogre doesn't support having different versions installed, so specifying
versions here doesn't work as expected.

2021-12-19 18:51 UTC, acxz commented
The `ogre=1.9` is required since certain packages list `ogre=1.9` as a dep such as (ros-noetic-rviz). Removing the `=1.9` means that there will be no package in the AUR that satisfies the `ogre=1.9` dep.

2021-12-19 19:36 UTC, rmsc commented
I see.

Then perhaps a `conflicts` entry is called for: https://wiki.archlinux.org/title/PKGBUILD#conflicts

2021-12-20 03:58 UTC, acxz commented
That's actually a great idea!

2021-12-20 03:59 UTC, acxz reviewed
Be sure to update the pkgrel, see: https://wiki.archlinux.org/title/PKGBUILD#pkgrel

Don't forget to update the .SRCINFO file as well, see: https://wiki.archlinux.org/title/.SRCINFO

2021-12-20 04:01 UTC, acxz requested changes
Be sure to update the pkgrel, see: https://wiki.archlinux.org/title/PKGBUILD#pkgrel

Don't forget to update the .SRCINFO file as well, see: https://wiki.archlinux.org/title/.SRCINFO

2021-12-20 10:52 UTC, closed without merging

2021-12-20 10:52 UTC, rmsc commented
Closing in favor of #158