pagmo 2.19.0
acxz/pkgbuilds pull request #222
Opened 2023-01-25 17:57 UTC by xantares

2023-01-26 17:10 UTC, acxz requested changes
Thanks for the PR @xantares.
One more thing to change however. Can you update the .SRCINFO file as well?

2023-01-27 18:19 UTC, xantares commented
ok, done

2023-02-09 05:47 UTC, xantares commented
ping @acxz

2023-02-22 13:45 UTC, acxz approved these changes
lgtm! sorry, slowly getting back to gh after vaycay

2023-02-22 13:45 UTC, merged