Fix python-mlflow build
acxz/pkgbuilds pull request #226
Opened 2023-02-27 12:18 UTC by AndreasHoermandinger

Should fix #187

2023-02-28 18:27 UTC, acxz requested changes
Thanks for the fix!

Just a couple of bookkeeping.
Can you bump the `pkgrel` by 1 and update the .SRCINFO? This is so that the AUR understands that a new update has been made.

Also if npm is not needed can you remove it from the deps?

Thanks!

2023-03-06 02:41 UTC, AndreasHoermandinger commented
@acxz , sorry I had never published anything to AUR, fixed now :) 

> Also if npm is not needed can you remove it from the deps?

I wasn't sure whether some code calls `npm` internally, but I tested the build after having uninstalled `npm` and it worked.

2023-03-06 17:56 UTC, acxz approved these changes

2023-03-06 17:56 UTC, merged

2023-03-06 17:56 UTC, acxz commented
LGTM!